// typesSPIO.h
// This file is generated by Shroud 0.14.0. Do not edit.
//
// Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
// other Axom Project Developers. See the top-level LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
// For C users and C++ implementation

#ifndef TYPESSPIO_H
#define TYPESSPIO_H

// Shared with other Shroud wrapped libraries
#ifndef SHROUD_SHARED_H
  #define SHROUD_SHARED_H

enum SwigMemFlags
{
  SWIG_MEM_OWN = 0x01,
  SWIG_MEM_RVALUE = 0x02,
};

#endif  // SHROUD_SHARED_H

// splicer begin types.CXX_declarations
// splicer end types.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin types.C_declarations
// splicer end types.C_declarations

// helper capsule_data
struct s_SPIO_SHROUD_capsule_data
{
  void *addr;    /* address of C++ memory */
  int idtor;     /* index of destructor */
  int cmemflags; /* memory flags */
};
typedef struct s_SPIO_SHROUD_capsule_data SPIO_SHROUD_capsule_data;
#if 0

// C++ capsule SPIO_IOManager
struct s_SPIO_IOManager {
    axom::sidre::IOManager *addr;     // address of C++ memory
    int idtor;      // index of destructor
    int cmemflags;  // memory flags
};
typedef struct s_SPIO_IOManager SPIO_IOManager;
#endif

// C capsule SPIO_IOManager
struct s_SPIO_IOManager
{
  void *addr;     // address of C++ memory
  int idtor;      // index of destructor
  int cmemflags;  // memory flags
};
typedef struct s_SPIO_IOManager SPIO_IOManager;

void SPIO_SHROUD_memory_destructor(SPIO_SHROUD_capsule_data *cap);

#ifdef __cplusplus
}
#endif

#endif  // TYPESSPIO_H
