// utilSPIO.cpp
// This file is generated by Shroud 0.14.0. Do not edit.
//
// Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
// other Axom Project Developers. See the top-level LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)

#include "axom/sidre/spio/IOManager.hpp"
#include "typesSPIO.h"

#ifdef __cplusplus
extern "C" {
#endif

// Release library allocated memory.
void SPIO_SHROUD_memory_destructor(SPIO_SHROUD_capsule_data *cap)
{
  void *ptr = cap->addr;
  switch(cap->idtor)
  {
  case 0:  // --none--
  {
    // Nothing to delete
    break;
  }
  case 1:  // axom::sidre::IOManager
  {
    axom::sidre::IOManager *cxx_ptr = reinterpret_cast<axom::sidre::IOManager *>(ptr);
    delete cxx_ptr;
    break;
  }
  default:
  {
    // Unexpected case in destructor
    break;
  }
  }
  cap->addr = nullptr;
  cap->idtor = 0;  // avoid deleting again
  cap->cmemflags = cap->cmemflags & ~SWIG_MEM_OWN;
}

// axom::sidre::IOManager = axom::sidre::IOManager
void SPIO_IOManager_assign_IOManager(SPIO_IOManager *lhs_capsule, SPIO_IOManager *rhs_capsule)
{
  if(lhs_capsule->addr == nullptr)
  {
    /* LHS is unassigned */
    if(rhs_capsule->cmemflags & SWIG_MEM_RVALUE)
    {
      // Capture pointer from RHS, clear 'moving' flag.
      lhs_capsule->addr = rhs_capsule->addr;
      lhs_capsule->idtor = rhs_capsule->idtor;
      lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
    else
    {
      // Aliasing another class; clear ownership.
      lhs_capsule->addr = rhs_capsule->addr;
      lhs_capsule->idtor = 0;
      lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
    }
  }
  else if(rhs_capsule->addr == nullptr)
  {
    // Replace LHS with a null pointer.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SPIO_SHROUD_memory_destructor((SPIO_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = nullptr;
    lhs_capsule->idtor = 0;
    lhs_capsule->cmemflags = 0;
  }
  else if(lhs_capsule->addr == rhs_capsule->addr)
  {
    // Lhs-assignment: ignore.
  }
  else if(rhs_capsule->cmemflags & SWIG_MEM_RVALUE)
  {
    // Transferred ownership from a variable that's about to be lost.
    // Move-assign and delete the transient data.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SPIO_SHROUD_memory_destructor((SPIO_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = rhs_capsule->addr;
    lhs_capsule->idtor = rhs_capsule->idtor;
    lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
  }
  else
  {
    // RHS shouldn't be deleted, alias to LHS.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SPIO_SHROUD_memory_destructor((SPIO_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = rhs_capsule->addr;
    lhs_capsule->idtor = rhs_capsule->idtor;
    lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
  }
}

#ifdef __cplusplus
}
#endif
