# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

from packaging.version import Version

from benchpark.directives import maintainers, variant
from benchpark.openmpsystem import OpenMPCPUOnlySystem
from benchpark.paths import hardware_descriptions
from benchpark.system import System, compiler_def, compiler_section_for


class CscsEiger(System):

    maintainers("pearce8")

    id_to_resources = {
        "eiger": {
            "sys_cores_per_node": 128,
            "timeout": 30,
            "system_site": "cscs",
            "hardware_key": str(hardware_descriptions)
            + "/HPECray-zen2-Slingshot/hardware_description.yaml",
        }
    }

    variant(
        "compiler",
        default="gcc",
        description="Which compiler to use",
    )

    def __init__(self, spec):
        super().__init__(spec)
        self.programming_models = [OpenMPCPUOnlySystem()]

        self.gcc_version = Version("12.3.0")

        self.scheduler = "slurm"
        attrs = self.id_to_resources.get("eiger")
        for k, v in attrs.items():
            setattr(self, k, v)

    def compute_compilers_section(self):
        return compiler_section_for(
            "gcc",
            [
                compiler_def(
                    "gcc@12.3.0 languages:=c,c++,fortran",
                    "/path/is/now/needed/",  # <-- TODO: this needs to be filled in
                    {"c": "cc", "cxx": "CC", "fortran": "ftn"},
                    modules=["PrgEnv-gnu", "gcc/12.3.0"],
                    compilers_use_relative_paths=True,
                )
            ],
        )

    def compute_packages_section(self):

        selections = {
            "packages": {
                "all": {"providers": {"mpi": ["cray-mpich"]}},
                "cray-mpich": {
                    "externals": [
                        {
                            "spec": "cray-mpich@8.1.28",
                            "prefix": "/user-environment/env/default",
                        }
                    ]
                },
            }
        }

        return selections

    def compute_software_section(self):
        """This is somewhat vestigial: for the Tioga config that is committed
        to the repo, multiple instances of mpi/compilers are stored and
        and these variables were used to choose consistent dependencies.
        The configs generated by this class should only ever have one
        instance of MPI etc., so there is no need for that. The experiments
        will fail if these variables are not defined though, so for now
        they are still generated (but with more-generic values).
        """
        return {
            "software": {
                "packages": {
                    "default-compiler": {"pkg_spec": "gcc@12.3.0"},
                    "default-mpi": {"pkg_spec": "cray-mpich@8.1.28"},
                    "compiler-gcc": {"pkg_spec": "gcc@12.3.0"},
                }
            }
        }
