// typesQUEST.h
// This file is generated by Shroud 0.14.0. Do not edit.
//
// Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
// other Axom Project Developers. See the top-level LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
// For C users and C++ implementation

#ifndef TYPESQUEST_H
#define TYPESQUEST_H

// Shared with other Shroud wrapped libraries
#ifndef SHROUD_SHARED_H
  #define SHROUD_SHARED_H

enum SwigMemFlags
{
  SWIG_MEM_OWN = 0x01,
  SWIG_MEM_RVALUE = 0x02,
};

#endif  // SHROUD_SHARED_H

// splicer begin types.CXX_declarations
// splicer end types.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin types.C_declarations
// splicer end types.C_declarations

// helper capsule_data
struct s_QUEST_SHROUD_capsule_data
{
  void *addr;    /* address of C++ memory */
  int idtor;     /* index of destructor */
  int cmemflags; /* memory flags */
};
typedef struct s_QUEST_SHROUD_capsule_data QUEST_SHROUD_capsule_data;

void QUEST_SHROUD_memory_destructor(QUEST_SHROUD_capsule_data *cap);

#ifdef __cplusplus
}
#endif

#endif  // TYPESQUEST_H
