// utilSLIC.cpp
// This file is generated by Shroud 0.14.0. Do not edit.
//
// Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
// other Axom Project Developers. See the top-level LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)

#include "axom/slic/streams/GenericOutputStream.hpp"
#include <string>
#include "typesSLIC.h"
#include <cstring>

#ifdef __cplusplus
extern "C" {
#endif

// helper copy_string
// Copy the char* or std::string in context into c_var.
// Called by Fortran to deal with allocatable character.
void SLIC_ShroudCopyString(SLIC_SHROUD_array *data, char *c_var, size_t c_var_len)
{
  const void *cxx_var = data->base_addr;
  size_t n = c_var_len;
  if(data->elem_len < n) n = data->elem_len;
  std::memcpy(c_var, cxx_var, n);
}

// Release library allocated memory.
void SLIC_SHROUD_memory_destructor(SLIC_SHROUD_capsule_data *cap)
{
  void *ptr = cap->addr;
  switch(cap->idtor)
  {
  case 0:  // --none--
  {
    // Nothing to delete
    break;
  }
  case 1:  // axom::slic::GenericOutputStream
  {
    axom::slic::GenericOutputStream *cxx_ptr =
      reinterpret_cast<axom::slic::GenericOutputStream *>(ptr);
    delete cxx_ptr;
    break;
  }
  case 2:  // std::string
  {
    std::string *cxx_ptr = reinterpret_cast<std::string *>(ptr);
    delete cxx_ptr;
    break;
  }
  case 3:  // new_string
  {
    std::string *cxx_ptr = reinterpret_cast<std::string *>(ptr);
    delete cxx_ptr;
    break;
  }
  default:
  {
    // Unexpected case in destructor
    break;
  }
  }
  cap->addr = nullptr;
  cap->idtor = 0;  // avoid deleting again
  cap->cmemflags = cap->cmemflags & ~SWIG_MEM_OWN;
}

// axom::slic::GenericOutputStream = axom::slic::GenericOutputStream
void SLIC_GenericOutputStream_assign_GenericOutputStream(SLIC_GenericOutputStream *lhs_capsule,
                                                         SLIC_GenericOutputStream *rhs_capsule)
{
  if(lhs_capsule->addr == nullptr)
  {
    /* LHS is unassigned */
    if(rhs_capsule->cmemflags & SWIG_MEM_RVALUE)
    {
      // Capture pointer from RHS, clear 'moving' flag.
      lhs_capsule->addr = rhs_capsule->addr;
      lhs_capsule->idtor = rhs_capsule->idtor;
      lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
    else
    {
      // Aliasing another class; clear ownership.
      lhs_capsule->addr = rhs_capsule->addr;
      lhs_capsule->idtor = 0;
      lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
    }
  }
  else if(rhs_capsule->addr == nullptr)
  {
    // Replace LHS with a null pointer.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SLIC_SHROUD_memory_destructor((SLIC_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = nullptr;
    lhs_capsule->idtor = 0;
    lhs_capsule->cmemflags = 0;
  }
  else if(lhs_capsule->addr == rhs_capsule->addr)
  {
    // Lhs-assignment: ignore.
  }
  else if(rhs_capsule->cmemflags & SWIG_MEM_RVALUE)
  {
    // Transferred ownership from a variable that's about to be lost.
    // Move-assign and delete the transient data.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SLIC_SHROUD_memory_destructor((SLIC_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = rhs_capsule->addr;
    lhs_capsule->idtor = rhs_capsule->idtor;
    lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
  }
  else
  {
    // RHS shouldn't be deleted, alias to LHS.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SLIC_SHROUD_memory_destructor((SLIC_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = rhs_capsule->addr;
    lhs_capsule->idtor = rhs_capsule->idtor;
    lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
  }
}

#ifdef __cplusplus
}
#endif
