#ifndef DET_MSG_H_
#define DET_MSG_H_

#include "common.h"

// Detector Messages
//  This unit defines a set of messages generated by the Detector module and
//    related components
//
// Copyright (C) 2021, Lawrence Livermore National Security, LLC.
//  All rights reserved. LLNL-CODE-837067
//
// The Department of Homeland Security sponsored the production of this
//  material under DOE Contract Number DE-AC52-07N427344 for the management
//  and operation of Lawrence Livermore National Laboratory. Contract no.
//  DE-AC52-07NA27344 is between the U.S. Department of Energy (DOE) and
//  Lawrence Livermore National Security, LLC (LLNS) for the operation of LLNL.
//  See license for disclaimers, notice of U.S. Government Rights and license
//  terms and conditions.

namespace tmon
{

struct CalibrationMsg
{
    using MsgClockType = std::chrono::system_clock;
    using MsgTimePointType = MsgClockType::time_point;
    enum class EventType
    {
        // Calibration period started
        start,
        // Calibration succeeded without constraint
        success,
        // Calibration partially succeeded: solution was constrained
        constrained_success,
        // Calibration failed; result rejected
        failure
    };
    CalibrationMsg()
        : msg_creation{MsgClockType::now()}
    {
    }
    CalibrationMsg(EventType type)
        : msg_creation{MsgClockType::now()}, evt_type{type}
    {
    }

    // Timestamp as of the creation of this message
    MsgTimePointType msg_creation;
    // Calibration event type
    EventType evt_type;
};

struct DetMetricMsg
{
    using MsgClockType = std::chrono::system_clock;
    using MsgTimePointType = MsgClockType::time_point;
    using MetricType = double;
    DetMetricMsg()
        : msg_creation{MsgClockType::now()}
    {
    }

    // Timestamp as of the creation of this message
    MsgTimePointType msg_creation;
    // Detection metric value
    MetricType det_metric;
    // Detection metric threshold value
    MetricType det_threshold;
};

std::string to_string(CalibrationMsg::EventType et);

} // end namespace

// Copyright (C) 2021, Lawrence Livermore National Security, LLC.
//  All rights reserved. LLNL-CODE-837067
//
// The Department of Homeland Security sponsored the production of this
//  material under DOE Contract Number DE-AC52-07N427344 for the management
//  and operation of Lawrence Livermore National Laboratory. Contract no.
//  DE-AC52-07NA27344 is between the U.S. Department of Energy (DOE) and
//  Lawrence Livermore National Security, LLC (LLNS) for the operation of LLNL.
//  See license for disclaimers, notice of U.S. Government Rights and license
//  terms and conditions.

#endif // DET_MSG_H_

