// utilSidre.cpp
// This file is generated by Shroud 0.14.0. Do not edit.
//
// Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
// other Axom Project Developers. See the top-level LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)

#include <string>
#include "axom/sidre/core/DataStore.hpp"
#include "typesSidre.h"

#ifdef __cplusplus
extern "C" {
#endif

// Release library allocated memory.
void SIDRE_SHROUD_memory_destructor(SIDRE_SHROUD_capsule_data *cap)
{
  void *ptr = cap->addr;
  switch(cap->idtor)
  {
  case 0:  // --none--
  {
    // Nothing to delete
    break;
  }
  case 1:  // std::string
  {
    std::string *cxx_ptr = reinterpret_cast<std::string *>(ptr);
    delete cxx_ptr;
    break;
  }
  case 2:  // axom::sidre::DataStore
  {
    axom::sidre::DataStore *cxx_ptr = reinterpret_cast<axom::sidre::DataStore *>(ptr);
    delete cxx_ptr;
    break;
  }
  default:
  {
    // Unexpected case in destructor
    break;
  }
  }
  cap->addr = nullptr;
  cap->idtor = 0;  // avoid deleting again
  cap->cmemflags = cap->cmemflags & ~SWIG_MEM_OWN;
}

// axom::sidre::Buffer = axom::sidre::Buffer
void SIDRE_Buffer_assign_Buffer(SIDRE_Buffer *lhs_capsule, SIDRE_Buffer *rhs_capsule)
{
  if(lhs_capsule->addr == nullptr)
  {
    /* LHS is unassigned */
    if(rhs_capsule->cmemflags & SWIG_MEM_RVALUE)
    {
      // Capture pointer from RHS, clear 'moving' flag.
      lhs_capsule->addr = rhs_capsule->addr;
      lhs_capsule->idtor = rhs_capsule->idtor;
      lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
    else
    {
      // Aliasing another class; clear ownership.
      lhs_capsule->addr = rhs_capsule->addr;
      lhs_capsule->idtor = 0;
      lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
    }
  }
  else if(rhs_capsule->addr == nullptr)
  {
    // Replace LHS with a null pointer.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SIDRE_SHROUD_memory_destructor((SIDRE_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = nullptr;
    lhs_capsule->idtor = 0;
    lhs_capsule->cmemflags = 0;
  }
  else if(lhs_capsule->addr == rhs_capsule->addr)
  {
    // Lhs-assignment: ignore.
  }
  else if(rhs_capsule->cmemflags & SWIG_MEM_RVALUE)
  {
    // Transferred ownership from a variable that's about to be lost.
    // Move-assign and delete the transient data.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SIDRE_SHROUD_memory_destructor((SIDRE_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = rhs_capsule->addr;
    lhs_capsule->idtor = rhs_capsule->idtor;
    lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
  }
  else
  {
    // RHS shouldn't be deleted, alias to LHS.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SIDRE_SHROUD_memory_destructor((SIDRE_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = rhs_capsule->addr;
    lhs_capsule->idtor = rhs_capsule->idtor;
    lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
  }
}

// axom::sidre::Group = axom::sidre::Group
void SIDRE_Group_assign_Group(SIDRE_Group *lhs_capsule, SIDRE_Group *rhs_capsule)
{
  if(lhs_capsule->addr == nullptr)
  {
    /* LHS is unassigned */
    if(rhs_capsule->cmemflags & SWIG_MEM_RVALUE)
    {
      // Capture pointer from RHS, clear 'moving' flag.
      lhs_capsule->addr = rhs_capsule->addr;
      lhs_capsule->idtor = rhs_capsule->idtor;
      lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
    else
    {
      // Aliasing another class; clear ownership.
      lhs_capsule->addr = rhs_capsule->addr;
      lhs_capsule->idtor = 0;
      lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
    }
  }
  else if(rhs_capsule->addr == nullptr)
  {
    // Replace LHS with a null pointer.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SIDRE_SHROUD_memory_destructor((SIDRE_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = nullptr;
    lhs_capsule->idtor = 0;
    lhs_capsule->cmemflags = 0;
  }
  else if(lhs_capsule->addr == rhs_capsule->addr)
  {
    // Lhs-assignment: ignore.
  }
  else if(rhs_capsule->cmemflags & SWIG_MEM_RVALUE)
  {
    // Transferred ownership from a variable that's about to be lost.
    // Move-assign and delete the transient data.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SIDRE_SHROUD_memory_destructor((SIDRE_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = rhs_capsule->addr;
    lhs_capsule->idtor = rhs_capsule->idtor;
    lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
  }
  else
  {
    // RHS shouldn't be deleted, alias to LHS.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SIDRE_SHROUD_memory_destructor((SIDRE_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = rhs_capsule->addr;
    lhs_capsule->idtor = rhs_capsule->idtor;
    lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
  }
}

// axom::sidre::View = axom::sidre::View
void SIDRE_View_assign_View(SIDRE_View *lhs_capsule, SIDRE_View *rhs_capsule)
{
  if(lhs_capsule->addr == nullptr)
  {
    /* LHS is unassigned */
    if(rhs_capsule->cmemflags & SWIG_MEM_RVALUE)
    {
      // Capture pointer from RHS, clear 'moving' flag.
      lhs_capsule->addr = rhs_capsule->addr;
      lhs_capsule->idtor = rhs_capsule->idtor;
      lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
    else
    {
      // Aliasing another class; clear ownership.
      lhs_capsule->addr = rhs_capsule->addr;
      lhs_capsule->idtor = 0;
      lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
    }
  }
  else if(rhs_capsule->addr == nullptr)
  {
    // Replace LHS with a null pointer.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SIDRE_SHROUD_memory_destructor((SIDRE_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = nullptr;
    lhs_capsule->idtor = 0;
    lhs_capsule->cmemflags = 0;
  }
  else if(lhs_capsule->addr == rhs_capsule->addr)
  {
    // Lhs-assignment: ignore.
  }
  else if(rhs_capsule->cmemflags & SWIG_MEM_RVALUE)
  {
    // Transferred ownership from a variable that's about to be lost.
    // Move-assign and delete the transient data.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SIDRE_SHROUD_memory_destructor((SIDRE_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = rhs_capsule->addr;
    lhs_capsule->idtor = rhs_capsule->idtor;
    lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
  }
  else
  {
    // RHS shouldn't be deleted, alias to LHS.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SIDRE_SHROUD_memory_destructor((SIDRE_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = rhs_capsule->addr;
    lhs_capsule->idtor = rhs_capsule->idtor;
    lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
  }
}

// axom::sidre::DataStore = axom::sidre::DataStore
void SIDRE_DataStore_assign_DataStore(SIDRE_DataStore *lhs_capsule, SIDRE_DataStore *rhs_capsule)
{
  if(lhs_capsule->addr == nullptr)
  {
    /* LHS is unassigned */
    if(rhs_capsule->cmemflags & SWIG_MEM_RVALUE)
    {
      // Capture pointer from RHS, clear 'moving' flag.
      lhs_capsule->addr = rhs_capsule->addr;
      lhs_capsule->idtor = rhs_capsule->idtor;
      lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
    else
    {
      // Aliasing another class; clear ownership.
      lhs_capsule->addr = rhs_capsule->addr;
      lhs_capsule->idtor = 0;
      lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
    }
  }
  else if(rhs_capsule->addr == nullptr)
  {
    // Replace LHS with a null pointer.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SIDRE_SHROUD_memory_destructor((SIDRE_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = nullptr;
    lhs_capsule->idtor = 0;
    lhs_capsule->cmemflags = 0;
  }
  else if(lhs_capsule->addr == rhs_capsule->addr)
  {
    // Lhs-assignment: ignore.
  }
  else if(rhs_capsule->cmemflags & SWIG_MEM_RVALUE)
  {
    // Transferred ownership from a variable that's about to be lost.
    // Move-assign and delete the transient data.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SIDRE_SHROUD_memory_destructor((SIDRE_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = rhs_capsule->addr;
    lhs_capsule->idtor = rhs_capsule->idtor;
    lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
  }
  else
  {
    // RHS shouldn't be deleted, alias to LHS.
    if(lhs_capsule->cmemflags & SWIG_MEM_OWN)
    {
      SIDRE_SHROUD_memory_destructor((SIDRE_SHROUD_capsule_data *)lhs_capsule);
    }
    lhs_capsule->addr = rhs_capsule->addr;
    lhs_capsule->idtor = rhs_capsule->idtor;
    lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
  }
}

#ifdef __cplusplus
}
#endif
