import argparse
import os
import subprocess
import sys
from pprint import pprint

import yaml
from deepdiff import DeepDiff

import benchpark.paths

sys.path.append(str(benchpark.paths.benchpark_home) + "/spack/lib/spack")
import llnl.util.tty.color as color  # noqa: E402


def load_yaml(file_path):
    """Load a YAML file and return its content as a Python object."""
    try:
        with open(file_path, "r") as file:
            return yaml.safe_load(file)
    except FileNotFoundError:
        print(f"Error: File not found: {file_path}")
        return None
    except yaml.YAMLError as e:
        print(f"Error: Failed to parse YAML file: {file_path}\n{e}")
        return None


def compare_yaml(file1, file2):
    """Compare two YAML files and print the differences."""

    def normalize_types(data):
        """fix to compare strings to int '56' == 56 for yaml purposes"""
        if isinstance(data, dict):
            # Fix specific keys and recursively normalize values
            tdict = {
                (k if k != "compilers:" else "compilers"): normalize_types(v)
                for k, v in data.items()
            }
            # Filter out problematic entries
            tdict = {
                k: v
                for k, v in tdict.items()
                if not (
                    isinstance(v, str)
                    and ("{self.cuda_version.major}" in v or "{self.cuda_version}" in v)
                )
            }
            return tdict
        elif isinstance(data, list):
            return [normalize_types(v) for v in data]
        elif isinstance(data, str) and data.isdigit():
            return int(data)  # Convert numeric strings to integers
        else:
            # Return other types as-is
            return data

    data1 = normalize_types(load_yaml(file1))
    data2 = normalize_types(load_yaml(file2))

    if data1 is None or data2 is None:
        color.cprint("\t\t@*rComparison aborted due to file loading errors.@.")
        return
    elif data1 == {} and data2 == {}:
        color.cprint("\t\t@*rDictionaries empty, aborting.@.")
        return

    # Use DeepDiff to find differences
    diff = DeepDiff(
        data1,
        data2,
        verbose_level=1,
        ignore_type_in_groups=[(int, str)],
        ignore_string_type_changes=True,
    )

    if not diff:
        color.cprint(f"\t\t@*gThe YAML files {file1} and {file2} are identical.@.")
    else:
        color.cprint(
            f"\t\t@*rThe YAML files {file1} and {file2} are different. Here are the differences:@."
        )
        pprint(diff)


def main():
    parser = argparse.ArgumentParser(
        description="""Compare YAMLs generated from 'system init' between two different commits of Benchpark.
Check if the configuration generated by 'system init' changed between commits.

(benchpark-python diffSystemSpecs.py -n newCommit)

Example usage:

    $ benchpark-python diffSystemSpecs.py -n myBranch
""",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument(
        "-o",
        "--old",
        type=str,
        default="develop",
        help="Commit hash or branch name for the old version of Benchpark (default: develop).",
    )
    parser.add_argument(
        "-n",
        "--new",
        type=str,
        required=True,
        help="Commit hash or branch name for the new version of Benchpark.",
    )
    parser.add_argument(
        "-s",
        "--systems",
        type=str,
        nargs="*",
        default=[
            "aws-pcluster",
            "csc-lumi",
            "cscs-daint",
            "cscs-eiger",
            "generic-x86",
            "jsc-juwels",
            # "lanl-venado",
            "llnl-cluster",
            "llnl-elcapitan",
            "llnl-sierra",
            "riken-fugaku",
        ],
        help="List of systems to include for comparison (default: all systems).",
    )

    args = parser.parse_args()

    # Use the arguments provided by the user or the defaults
    bp = {
        "benchpark-old": args.old,
        "benchpark-new": args.new,
    }

    # Define the sysd dictionary
    sysd = {
        "aws-pcluster": ["c6g.xlarge", "c4.xlarge", "hpc7a.48xlarge", "hpc6a.48xlarge"],
        "csc-lumi": None,
        "cscs-daint": None,
        "cscs-eiger": None,
        "generic-x86": None,
        "jsc-juwels": None,
        "lanl-venado": ["grace-hopper", "grace-grace"],
        "llnl-cluster": ["ruby", "magma", "dane"],
        "llnl-elcapitan": ["tioga", "elcapitan"],
        "llnl-sierra": None,
        "riken-fugaku": None,
    }

    # Filter sysd keys based on the provided systems argument
    sysd = {key: sysd[key] for key in args.systems if key in sysd}

    for name, tag in bp.items():

        if name not in os.listdir(os.getcwd()):
            subprocess.run(
                ["git", "clone", "https://github.com/LLNL/benchpark.git", name]
            )
        subprocess.run(["git", "checkout", tag], cwd=name)

        for system in sysd.keys():
            if not sysd[system]:
                subprocess.run(
                    [
                        "python",
                        f"{name}/lib/main.py",
                        "system",
                        "init",
                        f"--dest={name}/{system}",
                        system,
                    ]
                )
            else:
                var = "cluster"
                if system == "aws-pcluster":
                    var = "instance_type"
                for cluster in sysd[system]:
                    spec_list = [
                        "python",
                        f"{name}/lib/main.py",
                        "system",
                        "init",
                        f"--dest={name}/{cluster}",
                        system,
                        f"{var}={cluster}",
                    ]
                    subprocess.run(spec_list)

    # Compare the YAML files
    for system in sysd.keys():
        color.cprint("@*y" + system + "@.")
        iterable = sysd[system] if sysd[system] else [system]
        for cluster in iterable:
            for root, dirs, files in os.walk(f"benchpark-old/{cluster}"):
                loc = "/".join(root.split("/")[1:])
                for file in files:
                    color.cprint("\t@*b" + loc + "/" + file + "@.")
                    compare_yaml(
                        f"benchpark-old/{loc}/{file}",
                        f"benchpark-new/{loc}/{file}",
                    )


if __name__ == "__main__":
    main()
