{% set name = "trata" %}
{% set version = "1.0.0" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    # url: https://lc.llnl.gov/gitlab/weave/trata/archive/v{{ version }}.tar.gz
    # sha256: 

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - trata = trata:init

requirements:
  host:
    - python
  run:
    - python
    - scikit-learn
    - scipy
    - numpy

test:
  imports:
    - ibis
  commands:
    - pip check
  requires:
    - pip

about:
    home:  https://github.com/LLNL/trata
    summary: 
    license: BSD 3-Clause
    license_files: LICENSE

extra:
  maintainers:
     - olson59

