INSERT OR IGNORE INTO spdxlicensealias VALUES("Artistic-1.0", "Artistic");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-2.0", "GPL-2");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Apache-1.0", "Apache");
INSERT OR IGNORE INTO spdxlicensealias VALUES("LGPL-2.0", "LGPL-2");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-1.0", "GPL");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-1-Clause", "BSD");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-2.0-or-later", "GPL-2.1+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Python-2.0", "Python Software Foundation License");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-3.0", "GPL-3");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Apache-2.0", "Apache-2");
INSERT OR IGNORE INTO spdxlicensealias VALUES("LGPL-3.0", "LGPL-3");
INSERT OR IGNORE INTO spdxlicensealias VALUES("LGPL-2.0", "LGPL");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-2-Clause", "BSD-2-Clause-alike");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-3-Clause", "BSD-3-clause-with-patent-grant");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Artistic-2.0", "Artistic-2");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Apache-2.0", "Apache 2.0");
INSERT OR IGNORE INTO spdxlicensealias VALUES("LGPL-3.0", "LGPLv3");
INSERT OR IGNORE INTO spdxlicensealias VALUES("MIT", "MIT License");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-3-Clause", "BSD-3");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-2.0", "GPL v2");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-2.0", "GPL2");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-2.0+", "GPL2+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-1.0", "GPL-1");
INSERT OR IGNORE INTO spdxlicensealias VALUES("AFL-2.1", "AFLv2.1");
INSERT OR IGNORE INTO spdxlicensealias VALUES("LGPL-2.0+", "LGPL-2+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-3.0+", "GPLv3");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-2.0+", "GPL-2+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-3.0+", "GPL-3+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-3.0", "GNU GPL 3");
INSERT OR IGNORE INTO spdxlicensealias VALUES("LGPL-2.0+", "LGPLv2+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-2.0", "GPLv2");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GFDL-1.1", "GFDL");
INSERT OR IGNORE INTO spdxlicensealias VALUES("CC0-1.0", "CC0");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-1.0", "GNU GPL");
INSERT OR IGNORE INTO spdxlicensealias VALUES("PSF-2.0", "PSF");
INSERT OR IGNORE INTO spdxlicensealias VALUES("hdparm", "ARM");
INSERT OR IGNORE INTO spdxlicensealias VALUES("NIST-PD", "Public Domain");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Apache-2.0", "Apache License 2.0");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSL-1.0", "Boost");
INSERT OR IGNORE INTO spdxlicensealias VALUES("LGPL-2.0", "GNU LGPL");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-1.0+", "GPL-1+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-1.0+", "GGPL1+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-3.0+","GPL-3+-WITH-BISON-EXCEPTION"); -- may need some sort of splitting
INSERT OR IGNORE INTO spdxlicensealias VALUES("LGPL-3.0+", "LGPL-3+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-2.0+", "GPLv2+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-1.0", "GPL-");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-1.0", "GPL-any");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-3.0+", "GPLv3+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("LGPL-2.1", "LGPL2.1");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-1.0", "GPL-compatible");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-1.0+", "GPL1+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-2.0+", "GPL-2+~file");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-1.0", "GPL-unspecified");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-2.0", "GPL-2~either");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-2.0", "GPL-2~jack-audio-connection-kit");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-2.0", "GPL-2~jackd2");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-2.0", "GPL-2~or");
INSERT OR IGNORE INTO spdxlicensealias VALUES("LGPL-2.0", "LGPLv2");
INSERT OR IGNORE INTO spdxlicensealias VALUES("LGPL-3.0+", "LGPLv3+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GPL-1.0+", "GPL+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("LGPL-2.1+", "LGPL 2.1+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-3-Clause", "BSD-3-clause-GENERIC");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-3-Clause", "BSD-3-clause-with-weird-numbering");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-4-Clause", "BSD-4-clause-POWERDOG");
INSERT OR IGNORE INTO spdxlicensealias VALUES("bzip2-1.0.5", "BZIP");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Python-2.0.1", "Python");
INSERT OR IGNORE INTO spdxlicensealias VALUES("NIST-PD", "public-domain");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Unicode-3.0", "Custom-Unicode");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-2-Clause", "BSD-2-clause-author");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-2-Clause", "BSD-2-clause-verbatim");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-3-Clause", "BSD-3-clause-Peter-Wemm");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-3-Clause", "BSD-3-clause-Regents");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-4-Clause", "BSD-4-clause-Christopher-G-Demetriou");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-4-Clause", "BSD-4-clause-Niels-Provos");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-4-Clause", "BSD-5-clause-Peter-Wemm");
INSERT OR IGNORE INTO spdxlicensealias VALUES("ISC", "ISC-Original");
INSERT OR IGNORE INTO spdxlicensealias VALUES("NIST-PD", "public-domain-Colin-Plumb");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-2-Clause", "BSD-2-Clause-regents");
INSERT OR IGNORE INTO spdxlicensealias VALUES("MIT License", "MIT-Old-Style-with-legal-disclaimer-2");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GFDL-1.3-or-later", "GFDL-1.3+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-3-Clause", "BSD-3-clause-Cambridge");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-3-Clause", "BSD-3-clause-Smrgrav");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-3-Clause-Modification", "Modified_BSD");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Apache-1.0", "Apache License");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSL-1.0", "BSL");
INSERT OR IGNORE INTO spdxlicensealias VALUES("NIST-PD", "public-domain-1");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-1-Clause", "BSD licence");
INSERT OR IGNORE INTO spdxlicensealias VALUES("SGI-B-1.1", "SGI-1.1");
INSERT OR IGNORE INTO spdxlicensealias VALUES("SGI-B-2.0", "SGI-2");
INSERT OR IGNORE INTO spdxlicensealias VALUES("NIST-PD", "Public");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GFDL-1.1-no-invariants-only", "GFDL-NIV");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Apache-2.0", '"Apache-2.0";link="https://www.apache.org/licenses/LICENSE-2.0.txt"');
INSERT OR IGNORE INTO spdxlicensealias VALUES("APSL-1.1", "Apple");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GFDL-1.2-or-later", "GFDL-1.2+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("GFDL-1.1-or-later", "GFDL-1.1+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("MIT License", "MIT/X");
INSERT OR IGNORE INTO spdxlicensealias VALUES("AFL-1.1", "AFL");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Apache-1.0", "Apache Software License");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Artistic-2.0", "Artistic 2.0");
INSERT OR IGNORE INTO spdxlicensealias VALUES("OLDAP-1.1", "OpenLDAP");
INSERT OR IGNORE INTO spdxlicensealias VALUES("MPL-2.0", "MPLv2.0");
INSERT OR IGNORE INTO spdxlicensealias VALUES("PSF-2.0", "PSF-2");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-1-Clause", "Dual BSD");
INSERT OR IGNORE INTO spdxlicensealias VALUES("MPL-2.0", "Dual MIT");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-1-Clause", "BSD - See ndg");
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-1-Clause", "BSD-like");
INSERT OR IGNORE INTO spdxlicensealias VALUES("LGPL-2.0", "LGPL-");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Apache-2.0", '"Apache-2.0";link="https:');
INSERT OR IGNORE INTO spdxlicensealias VALUES("BSD-1-Clause", "U-OF-I-BSD-LIKE");
INSERT OR IGNORE INTO spdxlicensealias VALUES("CC-BY-SA-2.0", "CC-BY-SA-2.0-IT");
INSERT OR IGNORE INTO spdxlicensealias VALUES("CC-BY-SA-3.0", "CC-BY-SA-3.0-US");
INSERT OR IGNORE INTO spdxlicensealias VALUES("CC-BY-SA-3.0", "CC-BY-SA-3.0-Unported");
INSERT OR IGNORE INTO spdxlicensealias VALUES("NIST-PD", "public-domain~Kroon");
INSERT OR IGNORE INTO spdxlicensealias VALUES("IPL-1.0", "IBM");
INSERT OR IGNORE INTO spdxlicensealias VALUES("NIST-PD", "public-domain-md5");
INSERT OR IGNORE INTO spdxlicensealias VALUES("NIST-PD", "public-domain-s-s-d");
INSERT OR IGNORE INTO spdxlicensealias VALUES("App-s2p", "S2P");
INSERT OR IGNORE INTO spdxlicensealias VALUES("NIST-PD", "SDBM-PUBLIC-DOMAIN");
INSERT OR IGNORE INTO spdxlicensealias VALUES("HPND-MIT-disclaimer", "MIT-Old-Style-with-legal-disclaimer-2");
INSERT OR IGNORE INTO spdxlicensealias VALUES("LGPL-2.0-only", "LGPL-1.1+");
INSERT OR IGNORE INTO spdxlicensealias VALUES("NIST-PD", "solar-public-domain");
INSERT OR IGNORE INTO spdxlicensealias VALUES("ZPL-1.1", "ZPL");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Unicode-DFS-2015", "Unicode-data");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Inner-Net-2.0", "Inner-Net");
INSERT OR IGNORE INTO spdxlicensealias VALUES("Ubuntu-font-1.0", "Ubuntu");

