coverage:
  round: down
  range: 40...100
comment:
  layout: header, diff, changes, tree
  behavior: new
  require_changes: false
  require_base: false
  require_head: true
  after_n_builds: 10  # Number of SEPARATE codecov uploads expected, e.g. "Upload coverage to Codecov" jobs
