# autogenerated module using JSONSchema2Struct (author: I. Aravena, aravenasolis1@llnl.gov)
# timestamp: 2025-03-21T10:29:12.731

module CTMData

import JSON3, StructTypes

Base.@kwdef mutable struct TimeSeriesReference
    uid::Union{Int64, String}=0
    scale_factor::Float64=0.0
end

Base.@kwdef mutable struct XyPairs
    x::Vector{Float64}=Vector{Float64}()
    y::Vector{Float64}=Vector{Float64}()
end

Status = Int64

Uid = Any

NonnegativeInteger = Int64

Binary = Int64

PositiveInteger = Int64

NonnegativeNumber = Float64

PositiveNumber = Float64

Base.@kwdef mutable struct Load
    bus::Uid=Uid()
    qd_y::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    name::Union{Missing, String}=missing
    status::Status=Status()
    qd::Union{Float64, TimeSeriesReference}=0.0
    nominal_mva::Union{Missing, PositiveNumber}=missing
    uid::Uid=Uid()
    pd_y::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    pd_i::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    ext::Union{Missing, Any}=missing
    pd::Union{Float64, TimeSeriesReference}=0.0
    qd_i::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
end

Base.@kwdef mutable struct NetworkTransformer
    sm_ub_a::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    cm_ub_c::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    tm_lb::Union{Missing, PositiveNumber}=missing
    x::Float64=0.0
    b::Float64=0.0
    r::Float64=0.0
    sm_ub_c::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    name::Union{Missing, String}=missing
    status::Status=Status()
    persistent_outage_rate::Union{Missing, NonnegativeNumber}=missing
    persistent_outage_duration::Union{Missing, NonnegativeNumber}=missing
    tm_steps::Union{Missing, PositiveInteger}=missing
    sm_ub_b::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    g::Float64=0.0
    nominal_mva::Union{Missing, PositiveNumber}=missing
    uid::Uid=Uid()
    ta_steps::Union{Missing, PositiveInteger}=missing
    ext::Union{Missing, Any}=missing
    ta_ub::Union{Missing, Float64}=missing
    ta_lb::Union{Missing, Float64}=missing
    cm_ub_b::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    cm_ub_a::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    bus_to::Uid=Uid()
    bus_fr::Uid=Uid()
    tm_ub::Union{Missing, PositiveNumber}=missing
end

Base.@kwdef mutable struct NetworkShunt
    name::Union{Missing, String}=missing
    nominal_mva::Union{Missing, PositiveNumber}=missing
    status::Status=Status()
    uid::Uid=Uid()
    ext::Union{Missing, Any}=missing
    num_steps_ub::Union{NonnegativeInteger, Vector{NonnegativeInteger}}=NonnegativeInteger()
    gs::Union{NonnegativeNumber, Vector{NonnegativeNumber}}=NonnegativeNumber()
    bus::Uid=Uid()
    bs::Union{Float64, Vector{Float64}}=0.0
end

Base.@kwdef mutable struct NetworkGlobalParams
    bus_ref::Union{Missing, Uid}=missing
    base_mva::Union{Missing, PositiveNumber}=missing
    unit_convention::String=""
end

Base.@kwdef mutable struct Area
    name::Union{Missing, String}=missing
    status::Status=Status()
    uid::Uid=Uid()
    ext::Union{Missing, Any}=missing
end

Base.@kwdef mutable struct Reserve
    name::Union{Missing, String}=missing
    status::Status=Status()
    uid::Uid=Uid()
    ext::Union{Missing, Any}=missing
    pg_down::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    pg_up::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    participants::Union{Missing, Vector{Uid}}=missing
    reserve_type::String=""
end

Base.@kwdef mutable struct NetworkSwitch
    sm_ub::Union{Missing, NonnegativeNumber}=missing
    name::Union{Missing, String}=missing
    nominal_mva::Union{Missing, PositiveNumber}=missing
    cm_ub::Union{Missing, NonnegativeNumber}=missing
    status::Status=Status()
    uid::Uid=Uid()
    bus_to::Uid=Uid()
    bus_fr::Uid=Uid()
    ext::Union{Missing, Any}=missing
end

Base.@kwdef mutable struct NetworkStorage
    cm_ub::Union{Missing, NonnegativeNumber}=missing
    bus::Uid=Uid()
    charge_ub::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    energy_ub::Union{Missing, NonnegativeNumber}=missing
    name::Union{Missing, String}=missing
    status::Status=Status()
    ps_delta_ub::Union{Missing, NonnegativeNumber}=missing
    qs_lb::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    sm_ub::Union{Missing, NonnegativeNumber}=missing
    nominal_mva::Union{Missing, PositiveNumber}=missing
    uid::Uid=Uid()
    charge_efficiency::Union{Float64, TimeSeriesReference}=0.0
    ext::Union{Missing, Any}=missing
    qs_ex::Float64=0.0
    discharge_ub::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    ps_ex::Float64=0.0
    ps_delta_lb::Union{Missing, NonnegativeNumber}=missing
    discharge_efficiency::Union{Float64, TimeSeriesReference}=0.0
    qs_ub::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
end

Base.@kwdef mutable struct NetworkHvdcP2P
    loss_a::Union{Missing, NonnegativeNumber}=missing
    cm_ub_fr::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    pdc_fr_lb::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    qdc_fr_lb::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    r::Union{Missing, NonnegativeNumber}=missing
    phi_lb::Union{Missing, Float64}=missing
    loss_c::Union{Missing, NonnegativeNumber}=missing
    name::Union{Missing, String}=missing
    qdc_to_lb::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    status::Status=Status()
    pdc_to_lb::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    qdc_to_ub::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    technology::Union{Missing, String}=missing
    persistent_outage_rate::Union{Missing, NonnegativeNumber}=missing
    persistent_outage_duration::Union{Missing, NonnegativeNumber}=missing
    phi_ub::Union{Missing, Float64}=missing
    transient_outage_rate::Union{Missing, NonnegativeNumber}=missing
    sm_ub::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    nominal_mva::Union{Missing, PositiveNumber}=missing
    pdc_fr_ub::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    uid::Uid=Uid()
    ext::Union{Missing, Any}=missing
    base_kv_dc::Union{Missing, PositiveNumber}=missing
    loss_b::Union{Missing, NonnegativeNumber}=missing
    vm_dc_lb::Union{Missing, PositiveNumber}=missing
    pdc_to_ub::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    bus_to::Uid=Uid()
    bus_fr::Uid=Uid()
    qdc_fr_ub::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    cm_ub_to::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    vm_dc_ub::Union{Missing, PositiveNumber}=missing
    p::Union{Missing, Int64}=missing
end

Base.@kwdef mutable struct NetworkGen
    pg_delta_ub::Union{Missing, NonnegativeNumber}=missing
    primary_source::Union{Missing, String}=missing
    bus::Uid=Uid()
    pg_delta_lb::Union{Missing, NonnegativeNumber}=missing
    name::Union{Missing, String}=missing
    mean_time_to_failure::Union{Missing, NonnegativeNumber}=missing
    scheduled_maintenance_rate::Union{Missing, Float64}=missing
    status::Status=Status()
    shutdown_cost::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    down_time_lb::Union{Missing, NonnegativeNumber}=missing
    service_required::Union{Missing, Union{Int64, TimeSeriesReference}}=missing
    vm_setpoint::Union{Missing, Union{PositiveNumber, TimeSeriesReference}}=missing
    cost_pg_model::Union{Missing, String}=missing
    in_service_time_lb::Union{Missing, NonnegativeNumber}=missing
    qg_ub::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    in_service_time_ub::Union{Missing, NonnegativeNumber}=missing
    nominal_mva::Union{Missing, PositiveNumber}=missing
    cost_pg_parameters::Union{Missing, Union{Vector{Float64}, XyPairs, TimeSeriesReference}}=missing
    qg_lb::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    uid::Uid=Uid()
    startup_time_warm::Union{Missing, NonnegativeNumber}=missing
    forced_outage_rate::Union{Missing, Float64}=missing
    pg_lb::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    startup_cost_warm::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    ext::Union{Missing, Any}=missing
    primary_source_subtype::Union{Missing, String}=missing
    mean_time_to_repair::Union{Missing, NonnegativeNumber}=missing
    startup_cost_hot::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    pg_ub::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
    startup_time_hot::Union{Missing, NonnegativeNumber}=missing
    startup_cost_cold::Union{Missing, Union{Float64, TimeSeriesReference}}=missing
end

Base.@kwdef mutable struct AcLine
    sm_ub_a::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    cm_ub_c::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    x::Float64=0.0
    r::Float64=0.0
    vad_lb::Union{Missing, Float64}=missing
    sm_ub_c::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    name::Union{Missing, String}=missing
    status::Status=Status()
    persistent_outage_rate::Union{Missing, NonnegativeNumber}=missing
    persistent_outage_duration::Union{Missing, NonnegativeNumber}=missing
    g_to::Union{Missing, Float64}=missing
    transient_outage_rate::Union{Missing, NonnegativeNumber}=missing
    g_fr::Union{Missing, Float64}=missing
    b_fr::Union{Missing, Float64}=missing
    sm_ub_b::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    vad_ub::Union{Missing, Float64}=missing
    nominal_mva::Union{Missing, PositiveNumber}=missing
    uid::Uid=Uid()
    ext::Union{Missing, Any}=missing
    b_to::Union{Missing, Float64}=missing
    cm_ub_b::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    cm_ub_a::Union{Missing, Union{NonnegativeNumber, TimeSeriesReference}}=missing
    bus_to::Uid=Uid()
    bus_fr::Uid=Uid()
end

Base.@kwdef mutable struct NetworkMultipleWindingTransformer
    ta_ub_w::Union{Missing, Vector{Float64}}=missing
    num_windings::Int64=0
    r_w::Vector{Float64}=Vector{Float64}()
    cm_ub_b_w::Union{Missing, Vector{Union{NonnegativeNumber, TimeSeriesReference}}}=missing
    b::Float64=0.0
    tm_ub_w::Union{Missing, Vector{PositiveNumber}}=missing
    name::Union{Missing, String}=missing
    x_w::Vector{Float64}=Vector{Float64}()
    ta_lb_w::Union{Missing, Vector{Float64}}=missing
    status::Status=Status()
    ta_steps_w::Union{Missing, Vector{PositiveInteger}}=missing
    persistent_outage_rate::Union{Missing, NonnegativeNumber}=missing
    persistent_outage_duration::Union{Missing, NonnegativeNumber}=missing
    sm_ub_c_w::Union{Missing, Vector{Union{NonnegativeNumber, TimeSeriesReference}}}=missing
    cm_ub_a_w::Union{Missing, Vector{Union{NonnegativeNumber, TimeSeriesReference}}}=missing
    g::Float64=0.0
    nominal_mva_w::Union{Missing, Vector{PositiveNumber}}=missing
    sm_ub_b_w::Union{Missing, Vector{Union{NonnegativeNumber, TimeSeriesReference}}}=missing
    uid::Uid=Uid()
    bus_w::Vector{Uid}=Vector{Uid}()
    ext::Union{Missing, Any}=missing
    tm_lb_w::Union{Missing, Vector{PositiveNumber}}=missing
    tm_steps_w::Union{Missing, Vector{PositiveInteger}}=missing
    cm_ub_c_w::Union{Missing, Vector{Union{NonnegativeNumber, TimeSeriesReference}}}=missing
    sm_ub_a_w::Union{Missing, Vector{Union{NonnegativeNumber, TimeSeriesReference}}}=missing
    status_w::Vector{Status}=Vector{Status}()
end

Base.@kwdef mutable struct NetworkBus
    name::Union{Missing, String}=missing
    zone::Union{Missing, Uid}=missing
    status::Status=Status()
    uid::Uid=Uid()
    vm_ub::Union{Missing, Union{PositiveNumber, TimeSeriesReference}}=missing
    vm_lb::Union{Missing, Union{PositiveNumber, TimeSeriesReference}}=missing
    area::Union{Missing, Uid}=missing
    ext::Union{Missing, Any}=missing
    base_kv::PositiveNumber=PositiveNumber()
    type::Union{Missing, Union{String, TimeSeriesReference}}=missing
end

Base.@kwdef mutable struct Zone
    name::Union{Missing, String}=missing
    status::Status=Status()
    uid::Uid=Uid()
    ext::Union{Missing, Any}=missing
end

Base.@kwdef mutable struct TemporalBoundaryMultipleWindingTransformer
    uid::Uid=Uid()
    ext::Union{Missing, Any}=missing
    va_star_node::Float64=0.0
    ta_w::Any=nothing
    tm_w::Vector{PositiveNumber}=Vector{PositiveNumber}()
    vm_star_node::PositiveNumber=PositiveNumber()
end

Base.@kwdef mutable struct TemporalBoundaryBus
    va::Float64=0.0
    uid::Uid=Uid()
    vm::Union{Missing, PositiveNumber}=missing
    ext::Union{Missing, Any}=missing
end

Base.@kwdef mutable struct TemporalBoundaryHvdcP2P
    pdc_to::Float64=0.0
    qdc_fr::Union{Missing, Float64}=missing
    vm_dc_to::Union{Missing, PositiveNumber}=missing
    uid::Uid=Uid()
    pdc_fr::Float64=0.0
    ext::Union{Missing, Any}=missing
    vm_dc_fr::Union{Missing, PositiveNumber}=missing
    qdc_to::Union{Missing, Float64}=missing
end

Base.@kwdef mutable struct TemporalBoundarySwitch
    uid::Uid=Uid()
    ext::Union{Missing, Any}=missing
    state::Binary=Binary()
end

Base.@kwdef mutable struct TemporalBoundaryStorage
    qs::Union{Missing, Float64}=missing
    uid::Uid=Uid()
    ext::Union{Missing, Any}=missing
    energy::NonnegativeNumber=NonnegativeNumber()
    ps::Union{Missing, Float64}=missing
end

Base.@kwdef mutable struct TemporalBoundaryTransformer
    uid::Uid=Uid()
    ext::Union{Missing, Any}=missing
    tm::PositiveNumber=PositiveNumber()
    ta::Float64=0.0
end

Base.@kwdef mutable struct TemporalBoundaryGlobalParams
    time_elapsed::NonnegativeNumber=NonnegativeNumber()
end

Base.@kwdef mutable struct TemporalBoundaryShunt
    num_steps::Union{NonnegativeInteger, Vector{NonnegativeInteger}}=NonnegativeInteger()
    uid::Uid=Uid()
    ext::Union{Missing, Any}=missing
end

Base.@kwdef mutable struct TemporalBoundaryGen
    in_service_time::Union{Missing, NonnegativeNumber}=missing
    qg::Union{Missing, Float64}=missing
    pg::Float64=0.0
    uid::Uid=Uid()
    down_time::Union{Missing, NonnegativeNumber}=missing
    ext::Union{Missing, Any}=missing
end

Base.@kwdef mutable struct TimeSeriesData
    name::Union{Missing, Vector{String}}=missing
    path_to_file::Union{Missing, Union{String, Vector{String}}}=missing
    values::Union{Missing, Vector{Vector{Any}}}=missing
    uid::Vector{Uid}=Vector{Uid}()
    ext::Union{Missing, Vector{Any}}=missing
    timestamp::Union{Missing, Vector{NonnegativeNumber}}=missing
end

Base.@kwdef mutable struct Network
    zone::Union{Missing, Vector{Zone}}=missing
    bus::Vector{NetworkBus}=Vector{NetworkBus}()
    multiple_winding_transformer::Union{Missing, Vector{NetworkMultipleWindingTransformer}}=missing
    ac_line::Union{Missing, Vector{AcLine}}=missing
    gen::Vector{NetworkGen}=Vector{NetworkGen}()
    hvdc_p2p::Union{Missing, Vector{NetworkHvdcP2P}}=missing
    storage::Union{Missing, Vector{NetworkStorage}}=missing
    switch::Union{Missing, Vector{NetworkSwitch}}=missing
    reserve::Union{Missing, Vector{Reserve}}=missing
    area::Vector{Area}=Vector{Area}()
    global_params::NetworkGlobalParams=NetworkGlobalParams()
    shunt::Union{Missing, Vector{NetworkShunt}}=missing
    transformer::Union{Missing, Vector{NetworkTransformer}}=missing
    load::Vector{Load}=Vector{Load}()
end

Base.@kwdef mutable struct TemporalBoundary
    gen::Union{Missing, Vector{TemporalBoundaryGen}}=missing
    shunt::Union{Missing, Vector{TemporalBoundaryShunt}}=missing
    global_params::TemporalBoundaryGlobalParams=TemporalBoundaryGlobalParams()
    transformer::Union{Missing, Vector{TemporalBoundaryTransformer}}=missing
    storage::Union{Missing, Vector{TemporalBoundaryStorage}}=missing
    switch::Union{Missing, Vector{TemporalBoundarySwitch}}=missing
    hvdc_p2p::Union{Missing, Vector{TemporalBoundaryHvdcP2P}}=missing
    bus::Union{Missing, Vector{TemporalBoundaryBus}}=missing
    multiple_winding_transformer::Union{Missing, Vector{TemporalBoundaryMultipleWindingTransformer}}=missing
end

Base.@kwdef mutable struct Root
    ctm_version::String=""
    temporal_boundary::TemporalBoundary=TemporalBoundary()
    network::Network=Network()
    time_series_data::Union{Missing, TimeSeriesData}=missing
end

StructTypes.StructType(::Type{TimeSeriesReference}) = StructTypes.Mutable()
StructTypes.StructType(::Type{XyPairs}) = StructTypes.Mutable()
StructTypes.StructType(::Type{Load}) = StructTypes.Mutable()
StructTypes.StructType(::Type{NetworkTransformer}) = StructTypes.Mutable()
StructTypes.StructType(::Type{NetworkShunt}) = StructTypes.Mutable()
StructTypes.StructType(::Type{NetworkGlobalParams}) = StructTypes.Mutable()
StructTypes.StructType(::Type{Area}) = StructTypes.Mutable()
StructTypes.StructType(::Type{Reserve}) = StructTypes.Mutable()
StructTypes.StructType(::Type{NetworkSwitch}) = StructTypes.Mutable()
StructTypes.StructType(::Type{NetworkStorage}) = StructTypes.Mutable()
StructTypes.StructType(::Type{NetworkHvdcP2P}) = StructTypes.Mutable()
StructTypes.StructType(::Type{NetworkGen}) = StructTypes.Mutable()
StructTypes.StructType(::Type{AcLine}) = StructTypes.Mutable()
StructTypes.StructType(::Type{NetworkMultipleWindingTransformer}) = StructTypes.Mutable()
StructTypes.StructType(::Type{NetworkBus}) = StructTypes.Mutable()
StructTypes.StructType(::Type{Zone}) = StructTypes.Mutable()
StructTypes.StructType(::Type{TemporalBoundaryMultipleWindingTransformer}) = StructTypes.Mutable()
StructTypes.StructType(::Type{TemporalBoundaryBus}) = StructTypes.Mutable()
StructTypes.StructType(::Type{TemporalBoundaryHvdcP2P}) = StructTypes.Mutable()
StructTypes.StructType(::Type{TemporalBoundarySwitch}) = StructTypes.Mutable()
StructTypes.StructType(::Type{TemporalBoundaryStorage}) = StructTypes.Mutable()
StructTypes.StructType(::Type{TemporalBoundaryTransformer}) = StructTypes.Mutable()
StructTypes.StructType(::Type{TemporalBoundaryGlobalParams}) = StructTypes.Mutable()
StructTypes.StructType(::Type{TemporalBoundaryShunt}) = StructTypes.Mutable()
StructTypes.StructType(::Type{TemporalBoundaryGen}) = StructTypes.Mutable()
StructTypes.StructType(::Type{TimeSeriesData}) = StructTypes.Mutable()
StructTypes.StructType(::Type{Network}) = StructTypes.Mutable()
StructTypes.StructType(::Type{TemporalBoundary}) = StructTypes.Mutable()
StructTypes.StructType(::Type{Root}) = StructTypes.Mutable()

function parse(fname::String)::Root
    obj = open(fname, "r") do f
              JSON3.read(f, Root)
          end
    return obj
end

function remove_null_fields(fname::String)::Nothing
    run(pipeline(`grep -vwE '(: null)' $fname`, stdout=fname * "_tmp"))
    in_io = open(fname * "_tmp", "r")
    out_io = open(fname, "w")
    prev_ln = ""
    for ln in eachline(in_io)
        if prev_ln == ""        # first line
            prev_ln = ln
        elseif rstrip(prev_ln)[end] == ',' && lstrip(ln)[1] == '}'
            prev_ln = rstrip(prev_ln)[1:(end-1)]    # remove dangling comma
            println(out_io, prev_ln)
            prev_ln = ln
        else                    # nothing to do
            println(out_io, prev_ln)
            prev_ln = ln
        end
    end
    print(out_io, prev_ln)
    close(in_io)
    close(out_io)
    rm(fname * "_tmp")
end

function write(fname::String, x, omit_nulls::Bool=true)
    open(fname, "w") do f
        JSON3.pretty(f, x)
    end
    if omit_nulls
        remove_null_fields(fname)
    end
end

Int64() = Int64(0)
Float64() = Float64(0)
String() = ""
Bool() = false

Any() = nothing

end # module