version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - pandoc
    - graphviz

sphinx:
  configuration: docs/source/conf.py


formats:
    - pdf
    - epub

python:
    install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
