// typesSidre.h
// This file is generated by Shroud 0.14.0. Do not edit.
//
// Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
// other Axom Project Developers. See the top-level LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
// For C users and C++ implementation

#ifndef TYPESSIDRE_H
#define TYPESSIDRE_H

// Shared with other Shroud wrapped libraries
#ifndef SHROUD_SHARED_H
  #define SHROUD_SHARED_H

enum SwigMemFlags
{
  SWIG_MEM_OWN = 0x01,
  SWIG_MEM_RVALUE = 0x02,
};

#endif  // SHROUD_SHARED_H

// splicer begin types.CXX_declarations
// splicer end types.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin types.C_declarations
#include <axom/sidre/interface/SidreTypes.h>
// splicer end types.C_declarations

// helper capsule_data
struct s_SIDRE_SHROUD_capsule_data
{
  void *addr;    /* address of C++ memory */
  int idtor;     /* index of destructor */
  int cmemflags; /* memory flags */
};
typedef struct s_SIDRE_SHROUD_capsule_data SIDRE_SHROUD_capsule_data;
#if 0

// C++ capsule SIDRE_Buffer
struct s_SIDRE_Buffer {
    axom::sidre::Buffer *addr;     // address of C++ memory
    int idtor;      // index of destructor
    int cmemflags;  // memory flags
};
typedef struct s_SIDRE_Buffer SIDRE_Buffer;

// C++ capsule SIDRE_Group
struct s_SIDRE_Group {
    axom::sidre::Group *addr;     // address of C++ memory
    int idtor;      // index of destructor
    int cmemflags;  // memory flags
};
typedef struct s_SIDRE_Group SIDRE_Group;

// C++ capsule SIDRE_View
struct s_SIDRE_View {
    axom::sidre::View *addr;     // address of C++ memory
    int idtor;      // index of destructor
    int cmemflags;  // memory flags
};
typedef struct s_SIDRE_View SIDRE_View;

// C++ capsule SIDRE_DataStore
struct s_SIDRE_DataStore {
    axom::sidre::DataStore *addr;     // address of C++ memory
    int idtor;      // index of destructor
    int cmemflags;  // memory flags
};
typedef struct s_SIDRE_DataStore SIDRE_DataStore;
#endif

// C capsule SIDRE_Buffer
struct s_SIDRE_Buffer
{
  void *addr;     // address of C++ memory
  int idtor;      // index of destructor
  int cmemflags;  // memory flags
};
typedef struct s_SIDRE_Buffer SIDRE_Buffer;

// C capsule SIDRE_Group
struct s_SIDRE_Group
{
  void *addr;     // address of C++ memory
  int idtor;      // index of destructor
  int cmemflags;  // memory flags
};
typedef struct s_SIDRE_Group SIDRE_Group;

// C capsule SIDRE_View
struct s_SIDRE_View
{
  void *addr;     // address of C++ memory
  int idtor;      // index of destructor
  int cmemflags;  // memory flags
};
typedef struct s_SIDRE_View SIDRE_View;

// C capsule SIDRE_DataStore
struct s_SIDRE_DataStore
{
  void *addr;     // address of C++ memory
  int idtor;      // index of destructor
  int cmemflags;  // memory flags
};
typedef struct s_SIDRE_DataStore SIDRE_DataStore;

void SIDRE_SHROUD_memory_destructor(SIDRE_SHROUD_capsule_data *cap);

#ifdef __cplusplus
}
#endif

#endif  // TYPESSIDRE_H
