/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_llnl_lc_stg_ldapotp_LdapOtpNativeInterface */

#ifndef _Included_gov_llnl_lc_stg_ldapotp_LdapOtpNativeInterface
#define _Included_gov_llnl_lc_stg_ldapotp_LdapOtpNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_llnl_lc_stg_ldapotp_LdapOtpNativeInterface
 * Method:    OTP_is_otp
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_llnl_lc_stg_ldapotp_LdapOtpNativeInterface_OTP_1is_1otp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gov_llnl_lc_stg_ldapotp_LdapOtpNativeInterface
 * Method:    OTP_Authenticate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_llnl_lc_stg_ldapotp_LdapOtpNativeInterface_OTP_1Authenticate__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     gov_llnl_lc_stg_ldapotp_LdapOtpNativeInterface
 * Method:    OTP_Authenticate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Lgov/llnl/lc/stg/ldapotp/LdapOtpResponse;
 */
JNIEXPORT jobject JNICALL Java_gov_llnl_lc_stg_ldapotp_LdapOtpNativeInterface_OTP_1Authenticate__Ljava_lang_String_2Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
