#!/bin/sh     
#**************************************************************************
# test the example problems
# Author : Charles Tong
# Date   : 2007
#**************************************************************************
# use the Bourne shell to interpret script
#**************************************************************************

echo "Bungee Test: run global sensitivity analyses"
cd SimpleUQ/Bungee/Basic
../../../../build/bin/psuade < ./Scripts/psScript.in
/bin/rm -f ./psSave ./psuadeData* ./simulator ./*.m ./psuadeMetisInfo
cd ../../..

echo "Dimension Reduction Tests"
cd DimReduction/Morris20
echo "* Dimension Reduction Morris Test"
cc -o ./simulator ./simulator.c -lm
../../../build/bin/psuade < ./psMOATScript.in
echo "* Dimension Reduction Other Tests: Delta, SOT, MARS_SA"
../../../build/bin/psuade < ./psLHScript.in
/bin/rm -rf ./psuadeData* ./psSave* ./simulator ./*.m ./test.*
cd ../..

echo "Statistical Inference Tests"
cd StatInference/BasicTest/Test1
../../../../build/bin/psuade < ./psScriptMH.in
/bin/rm -rf ./simdata ./simulator ./*.m MCMCPostSample
cd ../../..

echo "Optimization/MOO"
cd Optimization/MOO
../../../build/bin/psuade < ./psScript.in
/bin/rm -rf ./*.m ./*_moo_*
cd ../..

echo "Optimization/Rosenbrock"
cd Optimization/Rosenbrock
cc -o simulator simulator.c -lm
../../../build/bin/psuade psuadeBobyqa.in 
echo "Rosenbrock: the answer should be all 1"
/bin/rm -rf ./psuadeData* ./simulator
cd ../..

