// Generated by DataCrumbs during system build
#include <datacrumbs/server/bpf/vmlinux.h>
// bpf headers
#include <bpf/bpf_core_read.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/usdt.bpf.h>

char LICENSE[] SEC("license") = "Dual BSD/GPL";

SEC("kprobe")
int BPF_KPROBE(kprobe_test) {
  return 0;
}

SEC("uprobe")
int BPF_UPROBE(uprobe_test) {
  return 0;
}

SEC("ksyscall")
int BPF_KSYSCALL(syscall_test, struct pt_regs* regs) {
  return 0;
}