#!/bin/sh

if [ -z "$PRI" ]; then
  d0=`dirname $0`
  ll=`ls -l $0`
  case $ll in
	  l*)  
		  f1=`echo $ll|awk '{print $NF}'`
		  d1=`dirname $f1`
		  PRI=`(cd $d0; cd $d1; echo $PWD)`
		  ;;
	  *)
		  PRI=`(cd $d0;echo $PWD)`
		  ;;
  esac
fi
if [ -z "$PY" ]; then
  export PATH=${PATH}:/usr/local/bin
  PY="python2.7"
  PYW="pythonw2.7"
fi

export PYTHONPATH=${PYTHONPATH}:\
${PRI}/PIL:\
${PRI}

if [ ! ${DYLD_LIBRARY_PATH} ]; then
   export DYLD_LIBRARY_PATH=${PRI}/wxPyLibs
else
   export DYLD_LIBRARY_PATH=${PRI}/wxPyLibs:${DYLD_LIBRARY_PATH}
fi

if   [ $# -eq 0 ]; then
    $PYW ${PRI}/Priithon/PriShell.py "$@"
elif [ "$1" = "-x" ]; then
    shift
    $PYW ${PRI}/Priithon/PriShell.py "$@"
elif [ "$1" = "-xc" ]; then
    $PYW ${PRI}/Priithon/PriShell.py "$@"
elif [ "$1" = "-xx" ]; then
	shift
    $PYW ${PRI}/Priithon/py/PyAlaMode.py "$@"
elif [ "$1" = "-ii" ]; then
	shift
    $PY -ic 'import IPython;IPython.Shell.IPShell().mainloop(1)' "$@"
else
	if [ -z "$PYTHONSTARTUP" ]; then
		export PYTHONSTARTUP=${PRI}/Priithon/startupPriithon.py
	fi
    $PYW "$@"
fi
