// Generated by DataCrumbs during system build
#include <datacrumbs/server/bpf/vmlinux.h>
// bpf headers
#include <bpf/bpf_core_read.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/usdt.bpf.h>
// internal headers
#include <datacrumbs/server/bpf/macros.bpf.h>
#include <datacrumbs/server/bpf/shared.h>

DATACRUMBS_MAP(pid_map, u32, u64, 1024);
DATACRUMBS_MAP(fn_pid_map, struct fn_key_t, struct fn_value_t);

#if defined(DATACRUMBS_MODE) && (DATACRUMBS_MODE == 1)
DATACRUMBS_MAP(failed_request, u32, u32, 128);
DATACRUMBS_RINGBUF(output, 1024 * 1024U * DATACRUMBS_TRACE_RINGBUF_SIZE_MB);
#else
DATACRUMBS_MAP(profile, struct profile_key_t, struct profile_value_t, 1024);
DATACRUMBS_MAP(usdt_profile, struct usdt_profile_key_t, struct profile_value_t, 1024);
DATACRUMBS_MAP(latest_interval, int, unsigned long long, 128);
#endif
DATACRUMBS_MAP(file_map, char[MAX_STR_READ_LEN], u32, 1024);
